connectorsConfigs:
  - inputType: kafka
    inputServiceConfigPath: /home/asto/egor/Processors/Host/config/input-kafka.yaml
    processors:
      - dll: /home/asto/egor/Processors/Implementation/ElasticSearch/ElasticProcessor/bin/Debug/net6.0/ElasticProcessor.dll
        config: /home/asto/egor/Processors/Host/config/processor-elastic.yaml
        name: Elasticsearch writer1
    proxyTypeMapper: KafkaToElastic
    outputType: combined
    outputServiceConfigPath: /home/asto/egor/Processors/Host/config/output-combined.yaml
  
  - inputType: kafka
    inputServiceConfigPath: /home/asto/egor/Processors/Host/config/input-errors-kafka.yaml
    processors:
      - dll: /home/asto/egor/Processors/Implementation/ElasticSearch/ElasticProcessor/bin/Debug/net6.0/ElasticProcessor.dll
        config: /home/asto/egor/Processors/Host/config/processor-elastic.yaml
        name: Elasticsearch writer1
    proxyTypeMapper: KafkaToElastic
    outputType: combined
    outputServiceConfigPath: /home/asto/egor/Processors/Host/config/output-combined.yaml
  
  - inputType: memory
    inputServiceConfigPath: /home/asto/egor/Processors/Host/config/input-memory.yaml
    processors:
      - dll: /home/asto/egor/Processors/Implementation/ElasticSearch/ElasticProcessor/bin/Debug/net6.0/ElasticProcessor.dll
        config: /home/asto/egor/Processors/Host/config/processor-elastic.yaml
        name: Elasticsearch writer1
    proxyTypeMapper: memoryToElastic
    outputType: combined
    outputServiceConfigPath: /home/asto/egor/Processors/Host/config/output-combined.yaml
