mode: oneByOneIfNotSuccess
outputServicesPathTypes:
  [
    { path: D:\Work\CBAP_1\Processors\Host\config\output-errors-kafka.yaml, type: kafka },
    { path: D:\Work\CBAP_1\Processors\Host\config\output-memory.yaml, type: memory },
  ]
toSendFilter:
  errors: true
  successes: false
  nullValues: false
