mode: oneByOneIfNotSuccess
outputServicesPathTypes:
  [
    { path: /home/asto/egor/Processors/Host/config/output-errors-kafka.yaml, type: kafka },
    { path: /home/asto/egor/Processors/Host/config/output-memory.yaml, type: memory },
  ]
toSendFilter:
  errors: true
  successes: false
  nullValues: false
